env:
  browser: true
  node: true
  es6: true
  jquery: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  react/jsx-uses-vars: 1
plugins:
  - react
